SELECT  
    p.PRODUCT_CODE AS PRODUCT_CODE, 
    p.PRICE * SUM(o.SALES_AMOUNT) AS SALES
FROM OFFLINE_SALE o 
JOIN PRODUCT p ON o.PRODUCT_ID = p.PRODUCT_ID
GROUP BY p.PRODUCT_CODE, p.PRICE
ORDER BY SALES DESC, PRODUCT_CODE;
