-- CAR_RENTAL_COMPANY_CAR : 대여 중인 자동차들의 정보
-- CAR_RENTAL_COMPANY_RENTAL_HISTORY : 자동차 대여 기록 정보
-- CAR_RENTAL_COMPANY_DISCOUNT_PLAN : 자동차 종류 별 대여 기간 종류 별 할인 정책 정보

SELECT c.CAR_ID, 
       c.CAR_TYPE,  
       ROUND((c.DAILY_FEE * 30 * ((100 - p.DISCOUNT_RATE) / 100)), 0) AS FEE
FROM CAR_RENTAL_COMPANY_CAR c
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN p 
ON c.CAR_TYPE = p.CAR_TYPE
WHERE c.CAR_TYPE IN ('SUV', '세단') AND p.DURATION_TYPE LIKE '30%'
AND NOT EXISTS (
    SELECT h.CAR_ID 
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY h
    WHERE h.CAR_ID = c.CAR_ID
    AND h.START_DATE <= '2022-11-30' 
    AND h.END_DATE >= '2022-11-01'
)
HAVING FEE BETWEEN 500000 AND 2000000
ORDER BY FEE DESC, c.CAR_TYPE ASC, c.CAR_ID DESC;

