-- 코드를 입력하세요
SELECT i.FOOD_TYPE, REST_ID, REST_NAME, j.FAVORITES
FROM REST_INFO i
JOIN (SELECT FOOD_TYPE, MAX(FAVORITES) AS FAVORITES
      FROM REST_INFO
      GROUP BY FOOD_TYPE) j
ON i.FOOD_TYPE = j.FOOD_TYPE AND i.FAVORITES = j.FAVORITES
ORDER BY FOOD_TYPE DESC;

