# -- 코드를 입력하세요
SELECT MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM REST_REVIEW r
JOIN MEMBER_PROFILE p
ON r.MEMBER_ID = p.MEMBER_ID
WHERE r.MEMBER_ID = (
    -- 가장 많이 리뷰를 작성한 MEMBER_ID 찾기
    SELECT MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    HAVING COUNT(*) = (
        -- 최대 리뷰 개수 찾기
        SELECT MAX(review_count)
        FROM (
            SELECT MEMBER_ID, COUNT(*) AS review_count
            FROM REST_REVIEW
            GROUP BY MEMBER_ID
        ) t
    )
    ORDER BY MEMBER_ID
    LIMIT 1
)
ORDER BY REVIEW_DATE, REVIEW_TEXT;

# SELECT MEMBER_ID, COUNT(*) AS TOTAL
# FROM REST_REVIEW
# GROUP BY MEMBER_ID
# ORDER BY TOTAL DESC;