-- 코드를 입력하세요
SELECT i.INGREDIENT_TYPE AS INGREDIENT_TYPE, SUM(TOTAL_ORDER) AS TOTAL_ORDER
FROM FIRST_HALF h JOIN ICECREAM_INFO i ON h.FLAVOR = i.FLAVOR
GROUP BY i.INGREDIENT_TYPE
ORDER BY TOTAL_ORDER;